version: '{build}'

# branches:
  # only:
  # - master

clone_depth: 5

environment:
  global:
    CL: -nologo -MP
  matrix:
  - GENERATOR: "Visual Studio 12 2013"
  - GENERATOR: "Visual Studio 12 2013 Win64"
  - GENERATOR: "Visual Studio 12 2013 ARM"
  - GENERATOR: "MSYS Makefiles"
  - GENERATOR: "Unix Makefiles"

matrix:
  fast_finish: true

install:
  # - cinst winflexbison
  # - win_flex --version
  # - win_bison --version
  - appveyor DownloadFile http://www.winpcap.org/install/bin/WpdPack_4_1_2.zip
  - 7z x .\WpdPack_4_1_2.zip -oc:\projects\libpcap\Win32

before_build:
  - set PATH=c:\msys64\MinGW64\bin;c:\msys64\usr\bin;%PATH%
  - flex --version
  - bison --version
  - touch .devel
  - mkdir build
  - cd build
  - cmake -DCMAKE_VS_PLATFORM_TOOLSET_HOST_ARCHITECTURE=x64 -DCMAKE_PREFIX_PATH=c:\projects\libpcap\Win32\WpdPack -G"%GENERATOR%" ..

build_script:
  - |
    for %%T in (INSTALL testprogs) do ( for %%C in (Debug Release RelWithDebInfo MinSizeRel) do ( appveyor AddMessage "Building %APPVEYOR_PROJECT_NAME% [Target: "%%T" and Configuration: "%%C"]" -Category Information -Details "APPVEYOR BUILD WORKER IMAGE: %APPVEYOR_BUILD_WORKER_IMAGE%" && cmake --build . --target %%T -- -nologo -maxcpucount -consoleloggerparameters:NoItemAndPropertyList;NoSummary;Verbosity=minimal -target:Rebuild -property:Configuration=%%C -logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" ) )

